### ISSUE TITLE
new database and database visualization

### ISSUE THREAD

**Issue by G2G2G2G** [awesome-foss/awesome-sysadmin#408]
new database system: https://github.com/surrealdb/surrealdb

database visualization.. there's no category for this not sure what to call it other than visualization https://github.com/azimuttapp/azimutt he calls it "ERD"  Entity Relationship diagram

**Comment by G2G2G2G** [comment]
Have you read your readme here? You have postgresql here.. surrealdb is another database engine.

**Comment by nodiscc** [comment]
Ok, let's add it to https://github.com/awesome-foss/awesome-sysadmin#rdbms

**Comment by G2G2G2G** [comment]
I'll make a PR but if we want to move database systems to the selfhosted (as technically they are closer to that) the viewers can stay here as that is more management or is that worse?

**Comment by nodiscc** [comment]
> if we want to move database systems

Database engines are now delegated to https://dbdb.io/ (https://github.com/awesome-foss/awesome-sysadmin/pull/437)

> the viewers can stay here

Indeed, we should add a section "Database Management Tools", I've listed Adminer as a candidate https://github.com/awesome-foss/awesome-sysadmin/issues/444

I don't think https://github.com/azimuttapp/azimutt should be added, as it is geared towards database design/development, which is IMHO outside the scope of this list.

Closing since nothing remains to do here.
